[package]
name: "bitswap-sdk"
description: "Bitswap SDK";
version: "1.0.0-alpha";
authors: ["<NAME> <<EMAIL>>"];
license: "MIT";
[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"


